### ISSUE TITLE
I would just like to mention that a lot of English typography style-guides advocate against superscript ordinal indicators

### ISSUE THREAD

**Issue by emilyyyylime** [extua/nth#1]
[Wikipedia]() compiles a good list of sources for that claim:
> In 19th-century handwriting, these terminals were often elevated, that is to say written as superscripts (e.g. 2<sup>nd</sup>, 34<sup>th</sup>). With the gradual introduction of the [typewriter](https://en.wikipedia.org/wiki/Typewriter) in the late 19th century, it became common to write them on the baseline in typewritten texts,[<sup>[15]</sup>](https://en.wikipedia.org/wiki/Ordinal_indicator#cite_note-15) and this usage even became recommended in certain 20th-century style guides. Thus, the 17th edition of [*The Chicago Manual of Style*](https://en.wikipedia.org/wiki/The_Chicago_Manual_of_Style) states: "The letters in ordinal numbers should not appear as superscripts (e.g., 122nd not 122<sup>nd</sup>)", as do the [*Bluebook*](https://en.wikipedia.org/wiki/Bluebook)[<sup>[16]</sup>](https://en.wikipedia.org/wiki/Ordinal_indicator#cite_note-TforL-16) and style guides by the [*Council of Science Editors*](https://en.wikipedia.org/wiki/Council_of_Science_Editors),[<sup>[17]</sup>](https://en.wikipedia.org/wiki/Ordinal_indicator#cite_note-17) [Microsoft](https://en.wikipedia.org/wiki/Microsoft_Manual_of_Style_for_Technical_Publications),[<sup>[18]</sup>](https://en.wikipedia.org/wiki/Ordinal_indicator#cite_note-18) and [Yahoo](https://en.wikipedia.org/wiki/Yahoo!).[<sup>[19]</sup>](https://en.wikipedia.org/wiki/Ordinal_indicator#cite_note-19) Two problems are that superscripts are used "most often in citations" and are "tiny and hard to read".[<sup>[16]</sup>](https://en.wikipedia.org/wiki/Ordinal_indicator#cite_note-TforL-16) Some [word processors] (https://en.wikipedia.org/wiki/Word_processor) format ordinal indicators as superscripts by default (e.g. [Microsoft Word](https://en.wikipedia.org/wiki/Microsoft_Word)[<sup>[20]</sup>](https://en.wikipedia.org/wiki/Ordinal_indicator#cite_note-20)). Style guide author Jack Lynch ([Rutgers](https://en.wikipedia.org/wiki/Rutgers_University)) recommends turning off automatic superscripting of ordinals in [Microsoft Word](https://en.wikipedia.org/wiki/Microsoft_Word), because "no professionally printed books use superscripts".[<sup>[21]</sup>](https://en.wikipedia.org/wiki/Ordinal_indicator#cite_note-21)

**Comment by emilyyyylime** [comment]
So the default in English should probably be no

..speaking of, is this internationalised at all? Might be worth to open another issue for that

**Comment by extua** [comment]
That's a good point, we could make no superscript the default, after introducing an argument to toggle superscript on or off. That's the only todo item in the readme file:

> Pass argument to choose whether or not to put ordinals in superscript.

As for internationalisation, it's only english ordinals for now, but worth creating an issue for other languages, I'm not sure how to approach different rules but will think about it.

**Comment by extua** [comment]
Coming back to this, we could add an argument for 'sup' along these lines:
```typst
#let nth(ordinal-num, sup: bool)
```

and then before writing out at the bottom of the function:

```typst
if sup == true {
    ordinal-str + super(ordinal-suffix)
  }
  else {
    ordinal-str + ordinal-suffix
  }
```

So if you wanted to have nth in superscript, you'd write

```typst
#nth(2422, sup: true)
```

Otherwise, omit the argument and get no superscript by default.

The only thing which bothers me about this is that including the argument each time is pretty onerous. @emilyyyylime do you know if there's a way of using `set` to set a default value at the top of the document, a bit like giving a series of arguments to `\usepackage` in LaTeX.

Or, we could provide a second function `nths`, which would just be a wrapper for `nth` with the argument added.

```typst
#let nths(ordinal) = {
  nth(ordinal, sup: true)
}
```

 This second way would be convenient to write, at the expense of breaking some programming conventions about pointless functions.

**Comment by emilyyyylime** [comment]
I mean, I think the default should just be set appropriately to style guides depending on the language, only overriding where explicitly given
